version: '3.8'

services:
  # PostgreSQL for structured data storage
  postgres:
    image: postgres:16-alpine
    container_name: ai_proxy_postgres
    environment:
      POSTGRES_USER: ai_proxy_user
      POSTGRES_PASSWORD: ai_proxy_password
      POSTGRES_DB: ai_proxy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_scripts:/docker-entrypoint-initdb.d  # For initialization scripts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai_proxy_user -d ai_proxy_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Qdrant for vector storage
  qdrant:
    image: qdrant/qdrant:latest
    container_name: ai_proxy_qdrant
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  qdrant_storage:
  pgadmin_data: